# Run `npm audit` every day at 13:00 (JST), which is 04:00 (UTC).
name: Daily npm audit

on:
  schedule:
    - cron: "0 4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions: {}

jobs:
  # Check job
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Check dependencies
        run: npm audit --audit-level=moderate
